load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
    name = "keylogger",
    srcs = ["main.cpp"],
    deps = [
        "//lib:keylogger-lib",
    ],
    visibility = ["//visibility:public"],
)
